### PR TITLE
Installation guide: update Arch and macOS

### PR DESCRIPTION
**Pull request by Funami580**

### CODE REVIEW

**Comment by CoffeeStraw** [comment]
Shouldn't we also update CI?
It still seems to work, so are the edits necessary?

**Comment by Funami580** [comment]
The macOS CI seems to already have Python 3 preinstalled. So it isn't necessary to change anything.

**Comment by CoffeeStraw** [comment]
It would be nice to stay coherent (if possible).
CI's code is often analyzed to help users debug something that went wrong during the installation process.

**Comment by Funami580** [comment]
Done.

**Comment by CoffeeStraw** [comment]
I've quickly reviewed the changes and I approve them!
Whenever you feel like you don't want to change anything else, I will merge this PR.

**Comment by Funami580** [comment]
That's all for now, you can merge this PR.

**Pull request merged**
