### PR TITLE
Add basic Linux support

### LINKED ISSUE #4: Linux Support
Right now, the library only works for Windows users. However, the library itself is ready for the implementation of Linux's support and shouldn't need any refactoring. More specifically, pretty much all the code is OS independent, except **text's rendering**, used to calculate text's metrics and positions. [Font utility](https://github.com/CoffeeStraw/PyonFX/blob/master/pyonfx/font_utility.py) file is the one dedicated to those operations.

### PR DESCRIPTION
**Pull request by Funami580**
Hi CoffeeStraw,

this pull request adds basic Linux support and is an attempt to fix #4. But please don't merge this pull request right away, there are still some things you might need to add or change. First of all, the Linux version depends on `cairo` and `pango`. Linux users might need to set up things first and maybe you also have to change your `setup.py` or `requirements.txt`.

These are some links that tell you how to set up cairo etc.:
* [pygobject](https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian)
* [pycairo](https://pycairo.readthedocs.io/en/latest/)

They worked fine for me on Python 3.6.

Also, I didn't test which of of all these you really need. I installed everything just in case, so you might have to check it by yourself.

In order to add Linux support, I basically just copied [Yutils](https://github.com/Youka/Yutils/blob/T1/src/Yutils.lua)' way to handle fonts on Linux, but I didn't check if the results correspond to the results from Windows. Perhaps you could compare them?

Kind regards

### CODE REVIEW

**Comment by CoffeeStraw** [comment]
Wow! Thank you for your amazing work, your PR was very detailed! An year as passed since I tried and put apart this issue, since I wasn't able to make the implementation work properly.

Unfortunately, at the moment I'm very busy working on my Bachelor's Thesis, and I could not be able to work on it soon :(

However, if it is not too much to ask, you could try run tests in a very simple way. I've written several tests for pyonfx functionalities [here](https://github.com/CoffeeStraw/PyonFX/tree/master/tests). To run them, you just need to:
1) Install pytest (you can easily do that with `pip install pytest`);
2) Move to the project directory where, for example, readme.md is;
3) Run the command `pytest`.

If you get no error or you get minor errors for some very small changes, you've implemented linux support in the right way!

**Comment by Funami580** [comment]
I fixed some bugs, but they didn't fix all the tests:
```
============================================================================ short test summary info =============================================================================
FAILED tests/test_ass.py::test_line_values
FAILED tests/test_convert.py::test_text_to_shape - NotImplementedError
```
I guess, we can ignore the NotImplementedError, right?
And regarding the test_ass.py:
```
==================================================================================== FAILURES ====================================================================================
________________________________________________________________________________ test_line_values ________________________________________________________________________________
FAILURE: 
assert 931.2134359692092 == 941.703125
tests/test_ass.py:42 in test_line_values() -> check.equal(line.width, 941.703125)
FAILURE: 
assert 36.98250524842547 == 36.984375
tests/test_ass.py:44 in test_line_values() -> check.equal(line.ascent, 36.984375)
FAILURE: 
assert 11.017494751574526 == 11.015625
tests/test_ass.py:45 in test_line_values() -> check.equal(line.descent, 11.015625)
FAILURE: 
assert 0.0 == 13.59375
tests/test_ass.py:46 in test_line_values() -> check.equal(line.internal_leading, 13.59375)
FAILURE: 
assert 0.0 == 3.09375
tests/test_ass.py:47 in test_line_values() -> check.equal(line.external_leading, 3.09375)
FAILURE: 
assert 174.3932820153954 == 169.1484375
tests/test_ass.py:50 in test_line_values() -> check.equal(line.left, 169.1484375)
FAILURE: 
assert 1105.6067179846045 == 1110.8515625
tests/test_ass.py:52 in test_line_values() -> check.equal(line.right, 1110.8515625)
------------------------------------------------------------
Failed Checks: 7
```
Ascent and descent are pretty close, but aren't equal with the value. But in my defence, these are the same values, Yutils prints out on Linux:
```
Ascent: 36.982505248425
Descend: 11.017494751575
Internal Leading: 0
External Leading: 0
Width: 931.21343596921
Height: 48
```
Here's the script, just in case you want to test it yourself:
```lua
script_name = "TestYutils"
script_description = "Test Yutils"
script_author = "Funami580"
script_version = "0.1"

Yutils = include("Yutils.lua")
include("karaskel.lua")

function font_vals(subtitles, selected)
    font_handle = Yutils.decode.create_font("Migu 1P", true, false, false, false, 48, 1, 1, 0)
    aegisub.debug.out("Ascent: " .. font_handle.metrics().ascent .. "\n")
    aegisub.debug.out("Descend: " .. font_handle.metrics().descent .. "\n")
    aegisub.debug.out("Internal Leading: " .. font_handle.metrics().internal_leading .. "\n")
    aegisub.debug.out("External Leading: " .. font_handle.metrics().external_leading .. "\n")
    extends = font_handle.text_extents("surechigau kotoba no ura ni tozasareta kokoro no kagi")
    aegisub.debug.out("Width: " .. extends.width .. "\n")
    aegisub.debug.out("Height: " .. extends.height .. "\n")
end

aegisub.register_macro(script_name, script_description, font_vals)
```
Also, could you write the `__del__` part? I really have no idea what to put in there.

**Comment by CoffeeStraw** [comment]
Well, this is very encouraging! You basically get everything working:
- We can definitely ignore `ascent` and `descent` values, I just need to change tests;
- It seems like `internal_leading` and `external_leading` can not be calculated on linux... Actually, they have a very limitated usage (they could only be usefull for some low-level calculations), so we can ignore them;
- My only concern is about the `width` value, which is very important for other calculations and should be as accurate as possible. Yutils is an outdated library, it is possible that those calculations are not correct anymore. However, it is also possible that those values renders correctly the text using libass on linux (even if I don't think so). We should try to produce some outputs (I would try producing the same output, but the first time using syls, second with chars and last with lines and check if the output is positioned always correctly).

Also, don't worry about the `__del__` part, I've written that for Windows to prevent overflow, I will write that for linux as well, I'll just need to do some testing after writing the code to assure that everything is working nicely.

Thank you again for your work, it seems like we're pretty close to a correct linux implementation.

**Comment by Funami580** [comment]
Well, I opened Aegisub and for some reason these values are correct:
with_border_left
with_border_right
Do you remember the test?
```
FAILURE: 
assert 174.3932820153954 == 169.1484375
tests/test_ass.py:50 in test_line_values() -> check.equal(line.left, 169.1484375)
FAILURE: 
assert 1105.6067179846045 == 1110.8515625
tests/test_ass.py:52 in test_line_values() -> check.equal(line.right, 1110.8515625)
```
174 and 1105 match the left and right bounding pretty well. Or did I do something wrong?

**Comment by CoffeeStraw** [comment]
Are you using Libass for rendering on Aegisub? If yes (and the Libass version in Aegisub is enough up to date), then... C O N G R A T S ! 🥳 
We now have a basic implementation of PyonFX for Linux fully working!

**Comment by CoffeeStraw** [comment]
Oh, I've seen closely your screen, this is not the correct way for checking. On the screen, you're checking the output of the script `examples/2 - Beginner/1 - First Simple Effect.py` right?

Well, that script output syllables, whose positions are calculated based on the initial width value of the line... So if the line was bad calculated, so are the syllables. You're basically checking if your possibly wrong value is equal to your possibly wrong value.

**Comment by Funami580** [comment]
Yeah, that's correct, I used this script. Ah damn, I knew that couldn't be right.

**Comment by Funami580** [comment]
I think I finally got a solution that's halfways working.
```
FAILURE: 
assert 941.7158852344296 == 941.703125
tests/test_ass.py:42 in test_line_values() -> check.equal(line.width, 941.703125)
FAILURE: 
assert 36.98250524842547 == 36.984375
tests/test_ass.py:44 in test_line_values() -> check.equal(line.ascent, 36.984375)
FAILURE: 
assert 11.017494751574526 == 11.015625
tests/test_ass.py:45 in test_line_values() -> check.equal(line.descent, 11.015625)
FAILURE: 
assert 0.0 == 13.59375
tests/test_ass.py:46 in test_line_values() -> check.equal(line.internal_leading, 13.59375)
FAILURE: 
assert 0.0 == 3.09375
tests/test_ass.py:47 in test_line_values() -> check.equal(line.external_leading, 3.09375)
FAILURE: 
assert 169.1420573827852 == 169.1484375
tests/test_ass.py:50 in test_line_values() -> check.equal(line.left, 169.1484375)
FAILURE: 
assert 1110.8579426172148 == 1110.8515625
tests/test_ass.py:52 in test_line_values() -> check.equal(line.right, 1110.8515625)
------------------------------------------------------------
Failed Checks: 7
```

**Comment by CoffeeStraw** [comment]
I think that your hack will not work if the style has letter_spacing > 0.
However it is a good idea, but still a hack...

**Comment by CoffeeStraw** [comment]
I should also add a test for width calculation of tests with style with some letter_spacing.

**Comment by Funami580** [comment]
> I should also add a test for width calculation of tests with style with some letter_spacing.

Yeah, that would be great. Could you also add tests for these tags?
* `\N` Multiline
* `\h` Hardspace
* `\q` Wrap style
* `\fs` Varying font sizes
* `\fscx` / `\fscy` Scaling
* `\bord` / `\xbord` / `\ybord` Border
* Bold / Italics / Underline / Strikethrough

**Comment by CoffeeStraw** [comment]
It is a good idea, but I can't atm. That's because PyonFX doesn't provide a way to parse tags in the line. Also, since Pyon is mainly designed for KFX creation, users are strongly discouraged to use those tags in a line.

**Comment by CoffeeStraw** [comment]
What we can do, is to create a .ass with different styles, and rewrite tests to try if all of them are rendered correctly.

**Comment by CoffeeStraw** [comment]
I'm sorry to ask you that, but could you please rebase your PR? 🙏

**Comment by Funami580** [comment]
I'll try that as soon as you provide the new tests.

**Comment by CoffeeStraw** [comment]
Hey there, sorry for the delay. In my [latest commit](https://github.com/CoffeeStraw/PyonFX/commit/c47c5cc8df979ceaad23e3b0a443dd6e5142bd12) I pushed a file with a lot of new tests for ass_core functionalities. Could you rebase and check how well you perform with your current linux implementation?

**Comment by Funami580** [comment]
Seems to work pretty well.
```
FAILURE: 
assert 0.0 == 13.59375 [ignore]
check.almost_equal(lines[1].internal_leading, 13.59375 or lines[1].internal_leading == 0.0, abs=0.5)
FAILURE: 
assert 0.0 == 3.09375 [ignore]
-> check.almost_equal(lines[1].external_leading, 3.09375 or lines[1].external_leading == 0.0, abs=0.5)
FAILURE: 
assert 612.2927921623512 == 612.8499999999999 [0.55 difference]
-> check.almost_equal(lines[6].width, 612.8499999999999, abs=0.5)
FAILURE: 
assert 820.202837232454 == 820.796875 [0.59 difference]
-> check.almost_equal(lines[8].width, 820.796875, abs=0.5)
FAILURE: 
assert 1090.202837232454 == 1090.796875 [0.59 difference]
-> check.almost_equal(lines[9].width, 1090.796875, abs=0.5)
FAILURE: 
assert 440.0 == 396.0
-> check.almost_equal(lines[12].height, 396.0, abs=0.5)
------------------------------------------------------------
Failed Checks: 6
```
Everything above a difference of 0.5 is a failure. But I guess we can ignore these slightly off values. But as you can see, it also says `assert 440.0 == 396.0`. Theoretically, this shouldn't happen. I could track the "bug" down, and here you go: `{\k56}す{\k13}れ{\k58}違{\k48}う{\k25}{\k67}言{\k50}葉{\k15}の{\k51}裏{\k49}に`. Basically, it's multiplying 44 (char height) times 10 (for ten syllables), but it should only be multiplied by 9. It's just that there's an empty syllable `{\k25}{\k67}`. Was that there before you uploaded the file?

**Comment by CoffeeStraw** [comment]
Yeah, it was there and it is pretty common to find empty syllables in k-times (see also lines[11], the romaji line). So it is important that your implementation pass this test. However, it seems to me like my vertical kanji calculations for line's width and height are wrong.

https://github.com/CoffeeStraw/PyonFX/blob/master/pyonfx/ass_core.py#L830-L833
These is the code that performs those calculations. Now that I think about it, vertical positioned lines could have two different values for both width and height, depending on whether user wanted to work with syllables or chars (if working with syllables, two or more chars may be at the same height, depending on how user has k-timed). So... how can we solve that issue?

**Comment by Funami580** [comment]
Uhm, is there a problem with just using a boolean?
https://github.com/CoffeeStraw/PyonFX/blob/master/pyonfx/ass_core.py#L416

**Comment by CoffeeStraw** [comment]
I can't put another boolean, since those booleans are taken before parsing and users use calculated width and height after parsing. In addition, an user could want to use both syls and chars for vertical kanjis.

**Comment by Funami580** [comment]
I don't quite get the first part. Why should it be a problem that it's taken before parsing? For example:
```python
io = Ass("in.ass", split_at_chars=True)
meta, styles, lines = io.get_data()
# Vertical text is now split at chars
```
But as you already mentioned, it wouldn't work for both splitting at syls and chars. But let me propose another way:
```python
io = Ass("in.ass")
meta, styles, lines = io.get_data()
styles["Vertical Text"].split_at_chars = True # or styles["Vertical Text"].split_at = SplitType.CHARS
```
You could also combine both, e. g.:
```python
io = Ass("in.ass", split_at=SplitType.CHARS) # Setting default to SplitType.CHARS
meta, styles, lines = io.get_data()
print(styles["Vertical Text"].split_at)  # -> SplitType.CHARS
styles["Syl Split"].split_at = SplitType.SYLLABLES
```
In the last two cases you'd have to recalculate the height, since it got parsed first and the style got changed afterwards. This would require to build in an observer and recalculate the lines after every style change, but that wouldn't be really efficient. Sure, it would only need some microseconds on a fast computer, but I guess that's not the solution you are seeking for, right?

So just in case you don't want to recalculate any values:
```python
io = Ass("in.ass")
meta, styles = io.get_data()
styles["Syl Split"].split_at = SplitType.SYLLABLES
lines = io.get_lines() # The lines are calculated the first time when calling this function
```
But in my opinion that doesn't look very clean. But how about something like this?
```python
from enum import Enum
from collections import UserList

class SplitType(Enum):
    CHARS = 1
    SYLLABLES = 2

class Line:
    height: int

class Style():
    def __init__(self, split_at):
        self.split_at = split_at

class LineList(UserList):
    def __init__(self, ass):
        super().__init__()
        self.ass = ass
        self.calculated = False
        print("LineList initialized")
    def __getitem__(self, key):
        if not self.calculated:
            self.calculated = True
            self.ass.calc_lines()
            print("Calculated lines")
        return super().__getitem__(key)

class Ass:
    def __init__(self, split_at=SplitType.CHARS):
        self.meta, self.styles, self.lines = None, {}, LineList(self)
        # Adding some dumb values
        self.styles["Vertical"] = Style(split_at)
        self.lines.extend([Line(), Line(), Line()])
    
    def get_data(self):
        return self.meta, self.styles, self.lines
    
    def calc_lines(self):
        # Some dumb calculations just for testing
        negative = self.styles["Vertical"].split_at == SplitType.SYLLABLES
        for i, line in enumerate(self.lines):
            line.height = 10 * i
            if negative:
                line.height = -line.height


# User script
io = Ass()
meta, styles, lines = io.get_data()

styles["Vertical"].split_at = SplitType.SYLLABLES  # Before: SplitType.CHARS

for line in lines:  # The calculation starts when __getitem__ is called the first time
    print(line.height)

'''
OUTPUT

LineList initialized
(Style is changed here)
Calculated lines
0
-10
-20
'''
```
A completely different approach would be to check if that box is checked and use that as indicator. But I don't really like this idea, it's not very intuitive and you may want to actually use this box.
box

But in the end it's up to you.

**Comment by CoffeeStraw** [comment]
I hadn't thought about the (last) implementation that you've done, good job!
However, that would change a little bit what a `Style object` is: right now is the exact representation of a Style in ASS format; with this edit, we will no longer be faithful to the ASS specification, which may make the library less intuitive and easy to use.

I think that the most commonly usage for vertical text is for "chars effects". So what I would do, is to calculate width and height with that in mind, specifying in the documentation that if user wants to make "syls effects" and needs width and height for those, will have to calculate them on his own.

**Comment by Funami580** [comment]
There's still one problem left. Why do I get a different height although we're running the same script?
```
assert 440.0 == 396.0
-> check.almost_equal(lines[12].height, 396.0, abs=0.5)
```

**Comment by CoffeeStraw** [comment]
Unfortunately, right now I can't help you on this part, since I don't have a working Linux partition.
To calculate line.height, we simply sum up each syllable height... Could you output your `line.syls` (referred to that particular line)?

**Comment by Funami580** [comment]
Sure.
```
[syls[0] (Syllable):
    i: 0
    word_i: 0
    start_time: 0
    end_time: 560
    duration: 560
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: す
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[1] (Syllable):
    i: 1
    word_i: 0
    start_time: 560
    end_time: 690
    duration: 130
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: れ
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[2] (Syllable):
    i: 2
    word_i: 0
    start_time: 690
    end_time: 1270
    duration: 580
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: 違
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[3] (Syllable):
    i: 3
    word_i: 0
    start_time: 1270
    end_time: 1750
    duration: 480
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: う
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[4] (Syllable):
    i: 4
    word_i: 0
    start_time: 1750
    end_time: 2000
    duration: 250
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: 
    postspace: 0
    width: 0.0
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[5] (Syllable):
    i: 5
    word_i: 0
    start_time: 2000
    end_time: 2670
    duration: 670
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: 言
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[6] (Syllable):
    i: 6
    word_i: 0
    start_time: 2670
    end_time: 3170
    duration: 500
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: 葉
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[7] (Syllable):
    i: 7
    word_i: 0
    start_time: 3170
    end_time: 3320
    duration: 150
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: の
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[8] (Syllable):
    i: 8
    word_i: 0
    start_time: 3320
    end_time: 3830
    duration: 510
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: 裏
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
, syls[9] (Syllable):
    i: 9
    word_i: 0
    start_time: 3830
    end_time: 4320
    duration: 490
    styleref (Style):
        fontname: Migu 1P
        fontsize: 44.0
        color1: &HFFFFFF&
        alpha1: &H00&
        color2: &H0000FF&
        alpha2: &H00&
        color3: &H000000&
        alpha3: &H00&
        color4: &H000000&
        alpha4: &H00&
        bold: True
        italic: False
        underline: False
        strikeout: False
        scale_x: 100.0
        scale_y: 100.0
        spacing: 0.0
        angle: 0.0
        border_style: False
        outline: 2.0
        shadow: 0.0
        alignment: 4
        margin_l: 25
        margin_r: 25
        margin_v: 25
        encoding: 1
    tags: 
    inline_fx: 
    prespace: 0
    text: に
    postspace: 0
    width: 31.52773536895674
    height: 44.0
    ascent: 33.90127226463104
    descent: 10.098727735368957
    internal_leading: 0.0
    external_leading: 0.0
]
```

**Comment by CoffeeStraw** [comment]
Ok, I found out the error, syls[4]:
image

**Comment by Funami580** [comment]
I added a new commit, everything should work now.
```
FAILURE: 
assert 0.0 == 13.59375 ± 5.0e-01
 +  where 13.59375 ± 5.0e-01 = <function approx at 0x7f27aa9e0a60>(13.59375, None, 0.5)
 +    where <function approx at 0x7f27aa9e0a60> = pytest.approx
test_ass.py:61 in test_line_values() -> check.almost_equal(lines[1].internal_leading, 13.59375 or lines[1].internal_leading == 0.0, abs=0.5)
FAILURE: 
assert 0.0 == 3.09375 ± 5.0e-01
 +  where 3.09375 ± 5.0e-01 = <function approx at 0x7f27aa9e0a60>(3.09375, None, 0.5)
 +    where <function approx at 0x7f27aa9e0a60> = pytest.approx
test_ass.py:62 in test_line_values() -> check.almost_equal(lines[1].external_leading, 3.09375 or lines[1].external_leading == 0.0, abs=0.5)
FAILURE: 
assert 612.2927921623512 == 612.8499999999999 ± 5.0e-01
 +  where 612.8499999999999 ± 5.0e-01 = <function approx at 0x7f27aa9e0a60>(612.8499999999999, None, 0.5)
 +    where <function approx at 0x7f27aa9e0a60> = pytest.approx
test_ass.py:89 in test_line_values() -> check.almost_equal(lines[6].width, 612.8499999999999, abs=0.5)
FAILURE: 
assert 820.202837232454 == 820.796875 ± 5.0e-01
 +  where 820.796875 ± 5.0e-01 = <function approx at 0x7f27aa9e0a60>(820.796875, None, 0.5)
 +    where <function approx at 0x7f27aa9e0a60> = pytest.approx
test_ass.py:97 in test_line_values() -> check.almost_equal(lines[8].width, 820.796875, abs=0.5)
FAILURE: 
assert 1090.202837232454 == 1090.796875 ± 5.0e-01
 +  where 1090.796875 ± 5.0e-01 = <function approx at 0x7f27aa9e0a60>(1090.796875, None, 0.5)
 +    where <function approx at 0x7f27aa9e0a60> = pytest.approx
test_ass.py:101 in test_line_values() -> check.almost_equal(lines[9].width, 1090.796875, abs=0.5)
------------------------------------------------------------
Failed Checks: 5
```

**Comment by CoffeeStraw** [comment]
Great! It is finally almost ready for merge, next week I'll find some time to review your code in detail.
I'll also need to update documentation for Linux implementation and, in a separate commit, I have to edit vertical text calculations (and update doc about it).

About tests, can you edit my test_ass.py in tests folder with your own edited version of tests? (The one which consider approximations. Also please provide a threshold value that is enough to pass al the tests)

**Comment by Funami580** [comment]
That's great! Regarding the test, what shall I do about `internal_leading` and `external_leading`? Perhaps something like this?
```python
if sys.platform == "win32":
    # Check internal and external leading here
    pass
```

**Comment by CoffeeStraw** [comment]
Yeah, only check for `internal_leading` and `external_leading` values on Windows!

**Comment by Funami580** [comment]
Here you go. You have to install pytest-check to run the test.
```
pip install pytest-check
```

**Comment by CoffeeStraw** [comment]
Thank you! I didn't know about "pytest-check", it seems much more comfortable than simple asserts! I have to remember to add that dependency to the project.

**Pull request merged**
