### PR TITLE
Rudimentary CI using Github Actions

### PR DESCRIPTION
**Pull request by cN3rd**
Currently runs on windows and doesn't do much but run a linter and the tests.
I want to try cleaning this up a little more and go over the linters/formatters to be used in the CI chain.

Please don't merge yet.

### CODE REVIEW

**Comment by CoffeeStraw** [comment]
Thank you for your work! :)
I'll be waiting for your merge request.

**Comment by CoffeeStraw** [comment]
Is this ready @cN3rd ?

**Comment by cN3rd** [comment]
Rebased it.

**Comment by CoffeeStraw** [comment]
Thank you very much!

**Pull request merged**
